"use client";
import { KpiCard, StatusBadge, CopyButton, ProgressBar } from "../shared";
import { DollarSign, MousePointer, ShoppingBag, Percent, Copy, BarChart3 } from "lucide-react";
const kpiData = [
  { label: "Total Earnings", value: "$12,450", trend: { value: "23.5%", direction: "up" as const }, context: "vs last month", iconColor: "primary" as const, icon: <DollarSign className="w-[18px] h-[18px]" /> },
  { label: "Total Clicks", value: "34,210", trend: { value: "18.2%", direction: "up" as const }, context: "vs last month", iconColor: "success" as const, icon: <MousePointer className="w-[18px] h-[18px]" /> },
  { label: "Conversions", value: "1,847", trend: { value: "12.8%", direction: "up" as const }, context: "vs last month", iconColor: "warning" as const, icon: <ShoppingBag className="w-[18px] h-[18px]" /> },
  { label: "Conversion Rate", value: "5.4%", trend: { value: "0.3%", direction: "down" as const }, context: "vs last month", iconColor: "danger" as const, icon: <Percent className="w-[18px] h-[18px]" /> },
];
const recentConversions = [
  { product: "Premium SaaS Plan", customer: "sarah.m@email.com", date: "May 12, 2026", amount: "$99.00", commission: "$19.80", status: "completed" as const },
  { product: "Pro Toolkit Bundle", customer: "mike.dev@email.com", date: "May 11, 2026", amount: "$49.00", commission: "$9.80", status: "completed" as const },
  { product: "Design Masterclass", customer: "anna.design@email.com", date: "May 10, 2026", amount: "$29.00", commission: "$5.80", status: "pending" as const },
  { product: "DevOps Course", customer: "tom.ops@email.com", date: "May 9, 2026", amount: "$199.00", commission: "$39.80", status: "completed" as const },
  { product: "Marketing Templates", customer: "lisa.mkt@email.com", date: "May 8, 2026", amount: "$19.00", commission: "$3.80", status: "refunded" as const },
];
const topProducts = [
  { name: "Premium SaaS Plan", sales: "234 sales", commission: "$4,680", rank: 1 },
  { name: "Pro Toolkit Bundle", sales: "189 sales", commission: "$3,780", rank: 2 },
  { name: "Design Masterclass", sales: "156 sales", commission: "$2,340", rank: 3 },
  { name: "DevOps Course", sales: "98 sales", commission: "$1,470", rank: 4 },
  { name: "Marketing Templates", sales: "87 sales", commission: "$870", rank: 5 },
];
export function AffiliateDashboard() {
  const referralLink = "https://referralx.com/ref/johndoe-pro-2024";
  return (<div className="space-y-6">
    <div className="bg-gradient-to-br from-rx-primary to-rx-primary-dark rounded-2xl px-8 py-7 text-white relative overflow-hidden"><div className="absolute -top-1/2 -right-[20%] w-[400px] h-[400px] bg-white/5 rounded-full"/><div className="relative z-10 flex items-center justify-between flex-wrap gap-4"><div><h2 className="text-2xl font-bold mb-1">Welcome back, John!</h2><p className="text-white/85 max-w-lg text-sm">You have earned <strong>$1,247.50</strong> this month. Your referral link generated <strong>3,421 clicks</strong> and <strong>87 conversions</strong>.</p></div><div className="flex gap-3"><CopyButton text={referralLink} label={<><Copy className="w-4 h-4"/> Copy Link</>}/><button className="px-4 py-2.5 border border-white/40 rounded-lg text-sm font-semibold hover:bg-white/10 flex items-center gap-2"><BarChart3 className="w-4 h-4"/> View Report</button></div></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-5">{kpiData.map(k=><KpiCard key={k.label} {...k}/>)}</div>
    <div className="bg-white rounded-2xl p-6 border border-rx-gray-200"><div className="flex items-center justify-between mb-4"><h3 className="text-base font-semibold text-rx-gray-800">Your Referral Link</h3><span className="inline-flex items-center gap-1.5 px-2.5 py-1 bg-rx-secondary-light text-rx-secondary rounded-full text-xs font-semibold"><span className="w-1.5 h-1.5 bg-rx-secondary rounded-full"/> Active</span></div><div className="flex gap-3 mb-4"><input type="text" value={referralLink} readOnly className="flex-1 px-4 py-3 border border-rx-gray-200 rounded-lg font-mono text-sm bg-rx-gray-50 text-rx-gray-700"/><CopyButton text={referralLink} label="Copy Link"/></div><div className="flex gap-6 pt-4 border-t border-rx-gray-100">{[{label:"Clicks (30d)",value:"3,421"},{label:"Conversions",value:"87"},{label:"Earnings",value:"$1,247.50"},{label:"Avg. Commission",value:"$14.34"}].map(s=><div key={s.label}><div className="text-xs text-rx-gray-500">{s.label}</div><div className="text-lg font-bold text-rx-gray-900">{s.value}</div></div>)}</div></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
      <div className="lg:col-span-2 bg-white rounded-2xl border border-rx-gray-200 p-5"><div className="flex items-center justify-between mb-5"><h3 className="text-base font-semibold text-rx-gray-800">Earnings Overview</h3><div className="flex gap-2">{["7D","30D","90D"].map((p,i)=><button key={p} className={`px-3 py-1.5 border rounded-lg text-xs font-medium ${i===0?"border-rx-primary text-rx-primary bg-rx-primary-light":"border-rx-gray-200 text-rx-gray-600"}`}>{p}</button>)}</div></div><div className="h-[300px] flex items-end gap-2 px-2">{[35,55,45,70,60,80,65,90,75,95,85,70].map((h,i)=><div key={i} className="flex-1 bg-gradient-to-t from-rx-primary to-rx-primary/60 rounded-t-md hover:from-rx-primary-dark hover:to-rx-primary transition-all" style={{height:`${h}%`}}/>)}</div><div className="flex justify-between mt-2 px-2 text-xs text-rx-gray-400">{["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"].map(m=><span key={m}>{m}</span>)}</div></div>
      <div className="bg-white rounded-2xl border border-rx-gray-200 p-5"><h3 className="text-base font-semibold text-rx-gray-800 mb-5">Top Products</h3><div className="space-y-3">{topProducts.map(p=><div key={p.name} className="flex items-center gap-3 p-3 rounded-lg hover:bg-rx-gray-50"><div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold ${p.rank===1?"bg-[#fef3c7] text-[#d97706]":p.rank===2?"bg-rx-gray-200 text-rx-gray-600":p.rank===3?"bg-[#ffedd5] text-[#c2410c]":"bg-rx-gray-100 text-rx-gray-600"}`}>{p.rank}</div><div className="flex-1 min-w-0"><div className="text-sm font-semibold text-rx-gray-800 truncate">{p.name}</div><div className="text-xs text-rx-gray-500">{p.sales}</div></div><div className="text-sm font-bold text-rx-secondary">{p.commission}</div></div>)}</div></div>
    </div>
    <div className="bg-white rounded-2xl p-6 border border-rx-gray-200"><div className="flex items-center justify-between mb-5"><h3 className="text-base font-semibold text-rx-gray-800">Payout Overview</h3></div><div className="grid grid-cols-1 md:grid-cols-3 gap-5">{[{label:"Available Balance",value:"$3,240.00",sub:"Ready to withdraw",progress:72},{label:"Pending Balance",value:"$890.50",sub:"Processing (3-5 days)",progress:35},{label:"Next Payout",value:"May 15, 2026",sub:"Minimum: $50.00",progress:100}].map(item=><div key={item.label} className="p-4 bg-rx-gray-50 rounded-xl"><div className="text-xs text-rx-gray-500 font-medium mb-1">{item.label}</div><div className="text-2xl font-bold text-rx-gray-900 mb-1">{item.value}</div><div className="text-xs text-rx-gray-400 mb-2">{item.sub}</div><ProgressBar value={item.progress} color="primary"/></div>)}</div></div>
    <div className="bg-white rounded-2xl border border-rx-gray-200 overflow-hidden"><div className="flex items-center justify-between px-5 py-4 border-b border-rx-gray-100"><h3 className="text-base font-semibold text-rx-gray-800">Recent Conversions</h3><div className="flex gap-2"><button className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-rx-gray-200 rounded-lg text-xs text-rx-gray-600 hover:bg-rx-gray-50">Filter</button><button className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-rx-gray-200 rounded-lg text-xs text-rx-gray-600 hover:bg-rx-gray-50">Export CSV</button></div></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-xs font-semibold uppercase tracking-wider text-rx-gray-500 bg-rx-gray-50"><th className="px-5 py-3">Product</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Commission</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{recentConversions.map((c,i)=><tr key={i} className="border-b border-rx-gray-100 last:border-0 hover:bg-rx-gray-50"><td className="px-5 py-3.5 text-sm font-semibold text-rx-gray-800">{c.product}</td><td className="px-5 py-3.5 text-sm text-rx-gray-700">{c.customer}</td><td className="px-5 py-3.5 text-sm text-rx-gray-500">{c.date}</td><td className="px-5 py-3.5 text-sm font-semibold text-rx-gray-900">{c.amount}</td><td className="px-5 py-3.5 text-sm font-bold text-rx-secondary">{c.commission}</td><td className="px-5 py-3.5"><StatusBadge status={c.status}/></td></tr>)}</tbody></table></div></div>
  </div>);
}
