"use client";
import { useState } from "react";
export function AffiliateSettings() {
  const [settings, setSettings] = useState({ emailNotifications:true, conversionAlerts:true, payoutAlerts:true, weeklyReport:true, monthlyReport:false, preferredMethod:"bank" });
  const toggle = (key: keyof typeof settings) => setSettings(prev=>({...prev,[key]:!prev[key]}));
  return (<div className="space-y-6">
    <div className="bg-white rounded-2xl p-6 border border-rx-gray-200"><h3 className="text-lg font-semibold text-rx-gray-800 mb-1">Profile Settings</h3><p className="text-sm text-rx-gray-500 mb-6">Update your personal information</p><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><div><label className="block text-sm font-medium text-rx-gray-700 mb-1.5">Full Name</label><input type="text" defaultValue="John Doe" className="w-full px-3.5 py-2.5 border border-rx-gray-200 rounded-lg text-sm focus:outline-none focus:border-rx-primary focus:ring-2 focus:ring-rx-primary-light"/></div><div><label className="block text-sm font-medium text-rx-gray-700 mb-1.5">Email</label><input type="email" defaultValue="john.doe@email.com" className="w-full px-3.5 py-2.5 border border-rx-gray-200 rounded-lg text-sm focus:outline-none focus:border-rx-primary focus:ring-2 focus:ring-rx-primary-light"/></div><div><label className="block text-sm font-medium text-rx-gray-700 mb-1.5">Phone</label><input type="tel" defaultValue="+1 (555) 123-4567" className="w-full px-3.5 py-2.5 border border-rx-gray-200 rounded-lg text-sm focus:outline-none focus:border-rx-primary focus:ring-2 focus:ring-rx-primary-light"/></div><div><label className="block text-sm font-medium text-rx-gray-700 mb-1.5">Timezone</label><select className="w-full px-3.5 py-2.5 border border-rx-gray-200 rounded-lg text-sm focus:outline-none focus:border-rx-primary focus:ring-2 focus:ring-rx-primary-light bg-white"><option>UTC-05:00 Eastern Time</option><option>UTC-08:00 Pacific Time</option><option>UTC+00:00 GMT</option><option>UTC+05:30 IST</option></select></div></div></div>
    <div className="bg-white rounded-2xl p-6 border border-rx-gray-200"><h3 className="text-lg font-semibold text-rx-gray-800 mb-1">Notification Settings</h3><p className="text-sm text-rx-gray-500 mb-6">Choose how you want to be notified</p><div className="space-y-1">{[{key:"emailNotifications" as const,label:"Email Notifications",desc:"Receive email alerts for important events"},{key:"conversionAlerts" as const,label:"Conversion Alerts",desc:"Get notified when you earn a commission"},{key:"payoutAlerts" as const,label:"Payout Alerts",desc:"Get notified about payout status changes"},{key:"weeklyReport" as const,label:"Weekly Report",desc:"Receive a weekly performance summary"},{key:"monthlyReport" as const,label:"Monthly Report",desc:"Receive a monthly performance summary"}].map(item=><div key={item.key} className="flex items-center justify-between py-4 border-b border-rx-gray-100 last:border-0"><div><div className="text-sm font-medium text-rx-gray-700">{item.label}</div><div className="text-xs text-rx-gray-500 mt-0.5">{item.desc}</div></div><button onClick={()=>toggle(item.key)} className={`w-11 h-6 rounded-full relative transition-colors ${settings[item.key]?"bg-rx-primary":"bg-rx-gray-300"}`}><span className={`absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${settings[item.key]?"translate-x-5":"translate-x-0"}`}/></button></div>)}</div></div>
    <div className="bg-white rounded-2xl p-6 border border-rx-gray-200"><h3 className="text-lg font-semibold text-rx-gray-800 mb-1">Payout Method</h3><p className="text-sm text-rx-gray-500 mb-6">Set your preferred payout method</p><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{[{id:"bank",label:"Bank Transfer",detail:"****4521"},{id:"paypal",label:"PayPal",detail:"john@email.com"},{id:"stripe",label:"Stripe",detail:"Not connected"}].map(method=><button key={method.id} onClick={()=>setSettings({...settings,preferredMethod:method.id})} className={`p-4 rounded-xl border-2 text-left transition-all ${settings.preferredMethod===method.id?"border-rx-primary bg-rx-primary-light":"border-rx-gray-200 hover:border-rx-gray-300"}`}><div className="text-sm font-semibold text-rx-gray-800">{method.label}</div><div className="text-xs text-rx-gray-500 mt-1">{method.detail}</div></button>)}</div></div>
    <div className="flex justify-end"><button className="px-6 py-2.5 bg-rx-primary text-white rounded-lg text-sm font-semibold hover:bg-rx-primary-dark">Save Changes</button></div>
  </div>);
}
