"use client";
import { StatusBadge } from "../shared";
import { CreditCard, Building, Wallet, Filter, Download, ArrowUpRight } from "lucide-react";
export function AffiliatePayouts() {
  return (<div className="space-y-6">
    <div className="bg-gradient-to-br from-rx-primary to-rx-primary-dark rounded-2xl p-8 text-white"><div className="flex items-center justify-between flex-wrap gap-4"><div><p className="text-white/70 text-sm mb-1">Available Balance</p><p className="text-4xl font-bold">$3,240.00</p><p className="text-white/60 text-sm mt-1">+$1,247.50 this month</p></div><button className="inline-flex items-center gap-2 px-6 py-3 bg-white text-rx-primary rounded-lg font-semibold hover:shadow-lg"><ArrowUpRight className="w-4 h-4"/> Request Payout</button></div></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-5">{[{icon:<Building className="w-5 h-5"/>,name:"Bank Transfer",detail:"****4521",status:"primary"},{icon:<CreditCard className="w-5 h-5"/>,name:"PayPal",detail:"john@email.com",status:"connected"},{icon:<Wallet className="w-5 h-5"/>,name:"Stripe",detail:"Not connected",status:"disconnected"}].map(m=><div key={m.name} className={`bg-white rounded-2xl p-6 border ${m.status==="disconnected"?"border-rx-gray-200 border-dashed":"border-rx-gray-200"}`}><div className="flex items-center gap-3 mb-3"><div className={`w-10 h-10 rounded-lg flex items-center justify-center ${m.status==="primary"?"bg-rx-primary-light text-rx-primary":m.status==="connected"?"bg-rx-secondary-light text-rx-secondary":"bg-rx-gray-100 text-rx-gray-400"}`}>{m.icon}</div><div><div className="text-sm font-semibold text-rx-gray-800">{m.name}</div><div className="text-xs text-rx-gray-500">{m.detail}</div></div></div>{m.status==="primary"&&<span className="text-xs font-semibold text-rx-primary">Default</span>}{m.status==="disconnected"&&<button className="text-xs font-semibold text-rx-primary hover:underline">Connect</button>}</div>)}</div>
    <div className="bg-white rounded-2xl border border-rx-gray-200 overflow-hidden"><div className="flex items-center justify-between px-5 py-4 border-b border-rx-gray-100"><h3 className="text-base font-semibold text-rx-gray-800">Payout History</h3><div className="flex gap-2"><button className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-rx-gray-200 rounded-lg text-xs text-rx-gray-600 hover:bg-rx-gray-50"><Filter className="w-3 h-3"/> Filter</button><button className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-rx-gray-200 rounded-lg text-xs text-rx-gray-600 hover:bg-rx-gray-50"><Download className="w-3 h-3"/> Export</button></div></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-xs font-semibold uppercase tracking-wider text-rx-gray-500 bg-rx-gray-50"><th className="px-5 py-3">Date</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Method</th><th className="px-5 py-3">Reference</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{[{date:"May 10, 2026",amount:"$495.00",method:"Bank Transfer",ref:"PAY-2026-089",status:"paid" as const},{date:"May 3, 2026",amount:"$285.00",method:"PayPal",ref:"PAY-2026-088",status:"paid" as const},{date:"Apr 26, 2026",amount:"$340.00",method:"Bank Transfer",ref:"PAY-2026-087",status:"paid" as const},{date:"Apr 19, 2026",amount:"$120.00",method:"PayPal",ref:"PAY-2026-086",status:"processing" as const},{date:"Apr 12, 2026",amount:"$75.00",method:"Bank Transfer",ref:"PAY-2026-085",status:"failed" as const}].map((p,i)=><tr key={i} className="border-b border-rx-gray-100 last:border-0 hover:bg-rx-gray-50"><td className="px-5 py-3.5 text-sm text-rx-gray-500">{p.date}</td><td className="px-5 py-3.5 text-sm font-semibold text-rx-gray-900">{p.amount}</td><td className="px-5 py-3.5 text-sm text-rx-gray-700">{p.method}</td><td className="px-5 py-3.5 text-sm text-rx-gray-500 font-mono">{p.ref}</td><td className="px-5 py-3.5"><StatusBadge status={p.status}/></td></tr>)}</tbody></table></div></div>
  </div>);
}
