"use client";
import { StatusBadge } from "../shared";
import { Receipt, Download, Mail, Eye, Filter } from "lucide-react";
export function AffiliateInvoices() {
  return (<div className="space-y-6">
    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
      <div className="bg-white rounded-2xl p-6 border border-rx-gray-200"><div className="flex items-center gap-3 mb-3"><div className="w-10 h-10 rounded-lg bg-rx-secondary-light flex items-center justify-center"><Receipt className="w-5 h-5 text-rx-secondary"/></div><div><div className="text-sm font-semibold text-rx-gray-800">Recent Invoice</div><div className="text-xs text-rx-gray-500">INV-2026-012</div></div></div><div className="text-2xl font-bold text-rx-gray-900 mb-1">$495.00</div><div className="text-xs text-rx-gray-500">May 10, 2026 - Paid</div></div>
      <div className="bg-white rounded-2xl p-6 border border-rx-gray-200"><div className="flex items-center gap-3 mb-3"><div className="w-10 h-10 rounded-lg bg-rx-warning-light flex items-center justify-center"><Receipt className="w-5 h-5 text-rx-warning"/></div><div><div className="text-sm font-semibold text-rx-gray-800">Pending Invoices</div><div className="text-xs text-rx-gray-500">2 invoices awaiting payment</div></div></div><div className="text-2xl font-bold text-rx-gray-900 mb-1">$195.00</div><div className="text-xs text-rx-gray-500">Total pending amount</div></div>
    </div>
    <div className="bg-white rounded-2xl border border-rx-gray-200 overflow-hidden"><div className="flex items-center justify-between px-5 py-4 border-b border-rx-gray-100"><h3 className="text-base font-semibold text-rx-gray-800">All Invoices</h3><button className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-rx-gray-200 rounded-lg text-xs text-rx-gray-600 hover:bg-rx-gray-50"><Filter className="w-3 h-3"/> Filter</button></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-xs font-semibold uppercase tracking-wider text-rx-gray-500 bg-rx-gray-50"><th className="px-5 py-3">Invoice</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Due Date</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Actions</th></tr></thead><tbody>{[{id:"INV-2026-012",date:"May 10, 2026",amount:"$495.00",due:"May 15, 2026",status:"paid" as const},{id:"INV-2026-011",date:"May 3, 2026",amount:"$285.00",due:"May 8, 2026",status:"paid" as const},{id:"INV-2026-010",date:"Apr 26, 2026",amount:"$340.00",due:"May 1, 2026",status:"paid" as const},{id:"INV-2026-009",date:"Apr 19, 2026",amount:"$120.00",due:"Apr 24, 2026",status:"pending" as const},{id:"INV-2026-008",date:"Apr 12, 2026",amount:"$75.00",due:"Apr 17, 2026",status:"pending" as const}].map(inv=><tr key={inv.id} className="border-b border-rx-gray-100 last:border-0 hover:bg-rx-gray-50"><td className="px-5 py-3.5 text-sm font-mono font-semibold text-rx-gray-800">{inv.id}</td><td className="px-5 py-3.5 text-sm text-rx-gray-500">{inv.date}</td><td className="px-5 py-3.5 text-sm font-semibold text-rx-gray-900">{inv.amount}</td><td className="px-5 py-3.5 text-sm text-rx-gray-500">{inv.due}</td><td className="px-5 py-3.5"><StatusBadge status={inv.status}/></td><td className="px-5 py-3.5"><div className="flex gap-1"><button className="p-1.5 rounded-lg hover:bg-rx-gray-100 text-rx-gray-400"><Eye className="w-4 h-4"/></button><button className="p-1.5 rounded-lg hover:bg-rx-gray-100 text-rx-gray-400"><Download className="w-4 h-4"/></button><button className="p-1.5 rounded-lg hover:bg-rx-gray-100 text-rx-gray-400"><Mail className="w-4 h-4"/></button></div></td></tr>)}</tbody></table></div></div>
  </div>);
}
