"use client";
import { KpiCard, ProgressBar } from "../shared";
import { DollarSign, TrendingUp, Wallet, Clock, Download, Filter } from "lucide-react";
const kpis = [
  { label: "Total Earnings", value: "$12,450", trend: { value: "23.5%", direction: "up" as const }, context: "vs last month", iconColor: "primary" as const, icon: <DollarSign className="w-[18px] h-[18px]" /> },
  { label: "This Month", value: "$1,247", trend: { value: "18.2%", direction: "up" as const }, context: "vs last month", iconColor: "success" as const, icon: <TrendingUp className="w-[18px] h-[18px]" /> },
  { label: "Available", value: "$3,240", trend: { value: "12.8%", direction: "up" as const }, context: "ready to withdraw", iconColor: "warning" as const, icon: <Wallet className="w-[18px] h-[18px]" /> },
  { label: "Pending", value: "$890", trend: { value: "5.1%", direction: "up" as const }, context: "processing", iconColor: "danger" as const, icon: <Clock className="w-[18px] h-[18px]" /> },
];
export function AffiliateEarnings() {
  return (<div className="space-y-6">
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-5">{kpis.map(k=><KpiCard key={k.label} {...k}/>)}</div>
    <div className="bg-white rounded-2xl border border-rx-gray-200 p-5"><div className="flex items-center justify-between mb-5"><h3 className="text-base font-semibold text-rx-gray-800">Earnings Over Time</h3><div className="flex gap-2">{["7D","30D","90D"].map((p,i)=><button key={p} className={`px-3 py-1.5 border rounded-lg text-xs font-medium ${i===1?"border-rx-primary text-rx-primary bg-rx-primary-light":"border-rx-gray-200 text-rx-gray-600"}`}>{p}</button>)}</div></div><div className="h-[300px] flex items-end gap-2 px-2">{[35,55,45,70,60,80,65,90,75,95,85,70].map((h,i)=><div key={i} className="flex-1 bg-gradient-to-t from-rx-secondary to-rx-secondary/60 rounded-t-md hover:from-[#059669] hover:to-rx-secondary transition-all" style={{height:`${h}%`}}/>)}</div><div className="flex justify-between mt-2 px-2 text-xs text-rx-gray-400">{["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"].map(m=><span key={m}>{m}</span>)}</div></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-5">{[{label:"Available Balance",value:"$3,240.00",sub:"Ready to withdraw",progress:72},{label:"Pending Balance",value:"$890.50",sub:"Processing (3-5 days)",progress:35},{label:"Lifetime Earnings",value:"$12,450.00",sub:"Since joining",progress:100}].map(item=><div key={item.label} className="bg-white rounded-2xl p-6 border border-rx-gray-200"><div className="text-xs text-rx-gray-500 font-medium mb-1">{item.label}</div><div className="text-2xl font-bold text-rx-gray-900 mb-1">{item.value}</div><div className="text-xs text-rx-gray-400 mb-3">{item.sub}</div><ProgressBar value={item.progress} color="success"/></div>)}</div>
    <div className="bg-white rounded-2xl border border-rx-gray-200 overflow-hidden"><div className="flex items-center justify-between px-5 py-4 border-b border-rx-gray-100"><h3 className="text-base font-semibold text-rx-gray-800">Earnings History</h3><div className="flex gap-2"><button className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-rx-gray-200 rounded-lg text-xs text-rx-gray-600 hover:bg-rx-gray-50"><Filter className="w-3 h-3"/> Filter</button><button className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-rx-gray-200 rounded-lg text-xs text-rx-gray-600 hover:bg-rx-gray-50"><Download className="w-3 h-3"/> Export</button></div></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-xs font-semibold uppercase tracking-wider text-rx-gray-500 bg-rx-gray-50"><th className="px-5 py-3">Date</th><th className="px-5 py-3">Source</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Balance</th></tr></thead><tbody>{[{date:"May 12, 2026",source:"Premium SaaS Plan",type:"Commission",amount:"$19.80",balance:"$3,240.00"},{date:"May 11, 2026",source:"Pro Toolkit Bundle",type:"Commission",amount:"$9.80",balance:"$3,220.20"},{date:"May 10, 2026",source:"Design Masterclass",type:"Commission",amount:"$5.80",balance:"$3,210.40"},{date:"May 9, 2026",source:"DevOps Course",type:"Commission",amount:"$39.80",balance:"$3,204.60"},{date:"May 8, 2026",source:"Marketing Templates",type:"Refund",amount:"-$3.80",balance:"$3,164.80"}].map((e,i)=><tr key={i} className="border-b border-rx-gray-100 last:border-0 hover:bg-rx-gray-50"><td className="px-5 py-3.5 text-sm text-rx-gray-500">{e.date}</td><td className="px-5 py-3.5 text-sm font-semibold text-rx-gray-800">{e.source}</td><td className="px-5 py-3.5"><span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${e.type==="Commission"?"bg-rx-secondary-light text-rx-secondary":"bg-rx-danger-light text-rx-danger"}`}>{e.type}</span></td><td className={`px-5 py-3.5 text-sm font-semibold ${e.amount.startsWith("-")?"text-rx-danger":"text-rx-secondary"}`}>{e.amount}</td><td className="px-5 py-3.5 text-sm font-semibold text-rx-gray-900">{e.balance}</td></tr>)}</tbody></table></div></div>
  </div>);
}
