"use client";
import { SectionCard } from "../shared";
import { FileText, DollarSign, Users, TrendingUp, BarChart3, Calendar, Download, Clock, RefreshCw } from "lucide-react";
const reports = [
  { icon: <DollarSign className="w-5 h-5"/>, color: "bg-rx-primary-light text-rx-primary", title: "Revenue Report", desc: "Detailed breakdown of all revenue streams", records: "1.2K", lastRun: "2 hours ago" },
  { icon: <Users className="w-5 h-5"/>, color: "bg-rx-secondary-light text-rx-secondary", title: "Affiliate Performance", desc: "Comprehensive analysis of affiliate activity", records: "856", lastRun: "4 hours ago" },
  { icon: <TrendingUp className="w-5 h-5"/>, color: "bg-rx-warning-light text-rx-warning", title: "Conversion Analysis", desc: "Track and analyze conversion funnels", records: "3.4K", lastRun: "1 day ago" },
  { icon: <BarChart3 className="w-5 h-5"/>, color: "bg-rx-info-light text-rx-info", title: "Traffic Sources", desc: "Understand where referrals are coming from", records: "2.1K", lastRun: "6 hours ago" },
  { icon: <FileText className="w-5 h-5"/>, color: "bg-rx-danger-light text-rx-danger", title: "Payout Summary", desc: "Overview of all payout transactions", records: "478", lastRun: "12 hours ago" },
  { icon: <Calendar className="w-5 h-5"/>, color: "bg-[#f3e8ff] text-[#9333ea]", title: "Monthly Trends", desc: "Month-over-month comparison of metrics", records: "12", lastRun: "1 day ago" },
];
export function AdminReports() {
  return (<div className="space-y-6">
    <div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold text-rx-gray-800">Analytics Reports</h3><p className="text-sm text-rx-gray-500">Generate and download comprehensive reports</p></div><div className="flex gap-2"><button className="inline-flex items-center gap-2 px-4 py-2 border border-rx-gray-200 rounded-lg text-sm text-rx-gray-600 hover:bg-rx-gray-50"><RefreshCw className="w-4 h-4"/> Refresh All</button><button className="inline-flex items-center gap-2 px-4 py-2 bg-rx-primary text-white rounded-lg text-sm font-semibold hover:bg-rx-primary-dark"><Clock className="w-4 h-4"/> Schedule Report</button></div></div>
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">{reports.map(r=><div key={r.title} className="bg-white rounded-2xl p-6 border border-rx-gray-200 hover:shadow-md hover:border-rx-primary/30 transition-all cursor-pointer"><div className={`w-12 h-12 rounded-lg flex items-center justify-center mb-4 ${r.color}`}>{r.icon}</div><h4 className="font-semibold text-rx-gray-800 mb-1">{r.title}</h4><p className="text-xs text-rx-gray-500 mb-4 leading-relaxed">{r.desc}</p><div className="flex gap-4 text-xs text-rx-gray-400"><span>{r.records} records</span><span>Last run: {r.lastRun}</span></div><div className="flex gap-2 mt-4 pt-4 border-t border-rx-gray-100"><button className="flex-1 py-2 text-sm font-medium text-rx-primary bg-rx-primary-light rounded-lg hover:bg-rx-primary/20">Generate</button><button className="flex-1 py-2 text-sm font-medium text-rx-gray-600 bg-rx-gray-50 rounded-lg hover:bg-rx-gray-100 flex items-center justify-center gap-1"><Download className="w-3.5 h-3.5"/> Download</button></div></div>)}</div>
    <SectionCard title="Recently Generated Reports" actions={<button className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-rx-gray-200 rounded-lg text-xs text-rx-gray-600 hover:bg-rx-gray-50"><Download className="w-3 h-3"/> Export All</button>}>
      <div className="overflow-x-auto -mx-5"><table className="w-full"><thead><tr className="text-left text-xs font-semibold uppercase tracking-wider text-rx-gray-500 border-b border-rx-gray-100"><th className="px-5 py-3">Report Name</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Generated</th><th className="px-5 py-3">Size</th><th className="px-5 py-3">Actions</th></tr></thead><tbody>{[{name:"Q1 Revenue Report",type:"Revenue",date:"May 10, 2026",size:"2.4 MB"},{name:"Affiliate Summary - April",type:"Affiliate",date:"May 1, 2026",size:"1.8 MB"},{name:"Conversion Funnel Analysis",type:"Conversion",date:"Apr 28, 2026",size:"3.1 MB"}].map((r,i)=><tr key={i} className="border-b border-rx-gray-100 last:border-0"><td className="px-5 py-3 text-sm font-semibold text-rx-gray-800">{r.name}</td><td className="px-5 py-3 text-sm text-rx-gray-600">{r.type}</td><td className="px-5 py-3 text-sm text-rx-gray-500">{r.date}</td><td className="px-5 py-3 text-sm text-rx-gray-500">{r.size}</td><td className="px-5 py-3"><button className="inline-flex items-center gap-1 text-xs text-rx-primary font-medium hover:underline"><Download className="w-3 h-3"/> Download</button></td></tr>)}</tbody></table></div>
    </SectionCard></div>);
}
