"use client";
import { useState } from "react";
import { SectionCard } from "../shared";
export function AdminSettings() {
  const [settings, setSettings] = useState({ programName:"ReferralX Default Program", commissionType:"percentage", commissionRate:"20", minimumPayout:"50", payoutSchedule:"monthly", emailNotifications:true, slackNotifications:false, newAffiliateAlert:true, payoutAlert:true, weeklyReport:true, monthlyReport:true, autoApprove:false, twoFactor:true });
  const toggle = (key: keyof typeof settings) => setSettings(prev=>({...prev,[key]:!prev[key]}));
  return (<div className="space-y-6">
    <SectionCard title="General Settings">
      <div className="space-y-5">
        <div><label className="block text-sm font-medium text-rx-gray-700 mb-1.5">Program Name</label><input type="text" value={settings.programName} onChange={e=>setSettings({...settings,programName:e.target.value})} className="w-full px-3.5 py-2.5 border border-rx-gray-200 rounded-lg text-sm focus:outline-none focus:border-rx-primary focus:ring-2 focus:ring-rx-primary-light"/></div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5"><div><label className="block text-sm font-medium text-rx-gray-700 mb-1.5">Commission Type</label><select value={settings.commissionType} onChange={e=>setSettings({...settings,commissionType:e.target.value})} className="w-full px-3.5 py-2.5 border border-rx-gray-200 rounded-lg text-sm focus:outline-none focus:border-rx-primary focus:ring-2 focus:ring-rx-primary-light bg-white"><option value="percentage">Percentage</option><option value="fixed">Fixed Amount</option></select></div><div><label className="block text-sm font-medium text-rx-gray-700 mb-1.5">Commission Rate / Amount</label><input type="text" value={settings.commissionRate} onChange={e=>setSettings({...settings,commissionRate:e.target.value})} className="w-full px-3.5 py-2.5 border border-rx-gray-200 rounded-lg text-sm focus:outline-none focus:border-rx-primary focus:ring-2 focus:ring-rx-primary-light"/></div></div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5"><div><label className="block text-sm font-medium text-rx-gray-700 mb-1.5">Minimum Payout</label><input type="text" value={settings.minimumPayout} onChange={e=>setSettings({...settings,minimumPayout:e.target.value})} className="w-full px-3.5 py-2.5 border border-rx-gray-200 rounded-lg text-sm focus:outline-none focus:border-rx-primary focus:ring-2 focus:ring-rx-primary-light"/></div><div><label className="block text-sm font-medium text-rx-gray-700 mb-1.5">Payout Schedule</label><select value={settings.payoutSchedule} onChange={e=>setSettings({...settings,payoutSchedule:e.target.value})} className="w-full px-3.5 py-2.5 border border-rx-gray-200 rounded-lg text-sm focus:outline-none focus:border-rx-primary focus:ring-2 focus:ring-rx-primary-light bg-white"><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select></div></div>
      </div>
    </SectionCard>
    <SectionCard title="Notification Preferences">
      <div className="space-y-1">{[{key:"emailNotifications" as const,label:"Email Notifications",desc:"Receive email alerts for important events"},{key:"slackNotifications" as const,label:"Slack Notifications",desc:"Send alerts to your Slack channel"},{key:"newAffiliateAlert" as const,label:"New Affiliate Alert",desc:"Get notified when a new affiliate signs up"},{key:"payoutAlert" as const,label:"Payout Request Alert",desc:"Get notified when a payout is requested"},{key:"weeklyReport" as const,label:"Weekly Report",desc:"Receive a weekly performance summary"},{key:"monthlyReport" as const,label:"Monthly Report",desc:"Receive a monthly performance summary"}].map(item=><div key={item.key} className="flex items-center justify-between py-4 border-b border-rx-gray-100 last:border-0"><div><div className="text-sm font-medium text-rx-gray-700">{item.label}</div><div className="text-xs text-rx-gray-500 mt-0.5">{item.desc}</div></div><button onClick={()=>toggle(item.key)} className={`w-11 h-6 rounded-full relative transition-colors ${settings[item.key]?"bg-rx-primary":"bg-rx-gray-300"}`}><span className={`absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${settings[item.key]?"translate-x-5":"translate-x-0"}`}/></button></div>)}</div>
    </SectionCard>
    <SectionCard title="Security">
      <div className="space-y-1">{[{key:"autoApprove" as const,label:"Auto-Approve Affiliates",desc:"Automatically approve new affiliate applications"},{key:"twoFactor" as const,label:"Two-Factor Authentication",desc:"Require 2FA for admin access"}].map(item=><div key={item.key} className="flex items-center justify-between py-4 border-b border-rx-gray-100 last:border-0"><div><div className="text-sm font-medium text-rx-gray-700">{item.label}</div><div className="text-xs text-rx-gray-500 mt-0.5">{item.desc}</div></div><button onClick={()=>toggle(item.key)} className={`w-11 h-6 rounded-full relative transition-colors ${settings[item.key]?"bg-rx-primary":"bg-rx-gray-300"}`}><span className={`absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full shadow-sm transition-transform ${settings[item.key]?"translate-x-5":"translate-x-0"}`}/></button></div>)}</div>
    </SectionCard>
    <div className="flex justify-end"><button className="px-6 py-2.5 bg-rx-primary text-white rounded-lg text-sm font-semibold hover:bg-rx-primary-dark">Save Changes</button></div>
  </div>);
}
