"use client";
import { Target, Users, DollarSign, Calendar, Plus, ArrowRight } from "lucide-react";
const programs = [
  { name: "Premium SaaS Plan", type: "Percentage - 20%", affiliates: 45, revenue: "$12,400", status: "Active", startDate: "Jan 1, 2026", endDate: "Dec 31, 2026", color: "from-rx-primary to-rx-primary-dark" },
  { name: "Pro Toolkit Bundle", type: "Fixed - $15/referral", affiliates: 32, revenue: "$8,900", status: "Active", startDate: "Feb 1, 2026", endDate: "Jul 31, 2026", color: "from-rx-secondary to-[#059669]" },
  { name: "Design Masterclass", type: "Percentage - 15%", affiliates: 28, revenue: "$5,200", status: "Active", startDate: "Mar 15, 2026", endDate: "Sep 15, 2026", color: "from-rx-warning to-[#d97706]" },
  { name: "DevOps Course", type: "Fixed - $25/referral", affiliates: 18, revenue: "$3,400", status: "Paused", startDate: "Apr 1, 2026", endDate: "Jun 30, 2026", color: "from-rx-info to-[#1d4ed8]" },
  { name: "Marketing Templates", type: "Percentage - 10%", affiliates: 15, revenue: "$1,800", status: "Draft", startDate: "May 1, 2026", endDate: "Aug 31, 2026", color: "from-rx-danger to-[#dc2626]" },
];
export function AdminPrograms() {
  return (<div className="space-y-6">
    <div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold text-rx-gray-800">Campaign Programs</h3><p className="text-sm text-rx-gray-500">Manage and monitor your referral programs</p></div><button className="inline-flex items-center gap-2 px-4 py-2.5 bg-rx-primary text-white rounded-lg text-sm font-semibold hover:bg-rx-primary-dark"><Plus className="w-4 h-4"/> Create Program</button></div>
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">{programs.map(p=><div key={p.name} className="bg-white rounded-2xl p-6 border border-rx-gray-200 hover:shadow-lg hover:-translate-y-0.5 transition-all relative overflow-hidden"><div className={`absolute top-0 left-0 right-0 h-1 bg-gradient-to-r ${p.color}`}/><div className="flex items-start justify-between mb-4"><div><h4 className="font-semibold text-rx-gray-800">{p.name}</h4><p className="text-xs text-rx-gray-500 mt-1">{p.type}</p></div><span className={`text-xs font-semibold px-2 py-1 rounded-full ${p.status==="Active"?"bg-rx-secondary-light text-rx-secondary":p.status==="Paused"?"bg-rx-warning-light text-rx-warning":"bg-rx-gray-100 text-rx-gray-500"}`}>{p.status}</span></div><div className="grid grid-cols-2 gap-4 mb-4"><div className="flex items-center gap-2"><Users className="w-4 h-4 text-rx-gray-400"/><div><div className="text-xs text-rx-gray-500">Affiliates</div><div className="text-lg font-bold text-rx-gray-900">{p.affiliates}</div></div></div><div className="flex items-center gap-2"><DollarSign className="w-4 h-4 text-rx-gray-400"/><div><div className="text-xs text-rx-gray-500">Revenue</div><div className="text-lg font-bold text-rx-gray-900">{p.revenue}</div></div></div></div><div className="flex items-center gap-2 text-xs text-rx-gray-500 mb-4"><Calendar className="w-3.5 h-3.5"/><span>{p.startDate} - {p.endDate}</span></div><div className="flex items-center justify-between pt-4 border-t border-rx-gray-100"><div className="flex -space-x-2">{["A","B","C"].map(i=><div key={i} className="w-7 h-7 rounded-full bg-gradient-to-br from-[#667eea] to-[#764ba2] border-2 border-white flex items-center justify-center text-white text-[10px] font-semibold">{i}</div>)}{p.affiliates>3&&<div className="w-7 h-7 rounded-full bg-rx-gray-100 border-2 border-white flex items-center justify-center text-rx-gray-600 text-[10px] font-semibold">+{p.affiliates-3}</div>}</div><span className="text-rx-primary text-[13px] font-semibold flex items-center gap-1 hover:gap-2 transition-all cursor-pointer">View Details <ArrowRight className="w-3 h-3"/></span></div></div>)}</div>
  </div>);
}
